name: Checks

on: [push, pull-request]

jobs:
  check:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test
      run: |
        python setup.py test
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 ./janome
    - name: Lint with mypy
      run: |
        pip install mypy
        mypy ./janome/tokenizer.py
        mypy ./janome/analyzer.py
        mypy ./janome/charfilter.py
        mypy ./janome/tokenfilter.py
    - name: Upload Coverage
      run: coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
        COVERALLS_PARALLEL: true

  coveralls:
    name: Finish Coveralls
    needs: check
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
